# petls-pytorch — GPU-native Persistent Topological Laplacians in PyTorch (S. K. Marston / Sylverity).
# INDEPENDENT Apache-2.0 reimplementation of the PETLS persistent-Laplacian engine; pure-Python universal
# wheel. In-repo recipe (noarch, redistributable) → L1 today, but conda-forge/Bioconda-eligible → L3/L4
# once the recipe lands in a public channel. The open, shippable alternative to unlicensed `petls` for
# every persistent-Laplacian pipeline. Drags a torch closure, so a full lockfile solve is heavy.
# Built from OUR FORK jmchilton/petls-pytorch @ v2 (isolated-vertex boundary fix + two other fixes; see the
# recipe header) — NOT the PyPI 1.0.2 sdist. The fork moved `tadasets` from a runtime dep to a benchmark
# extra, so this env no longer stages the sibling tadasets recipe (that recipe still backs `scikit-tda`).
[workspace]
preview = ["pixi-build"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[dependencies]
petls-pytorch = { path = "../../../recipes/petls-pytorch" }
